[package]
name = "verdi"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
readme = "README.md"
repository = "https://github.com/verdiwm/verdi"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
futures-util = { version = "0.3.30", default-features = false, features = [
    "sink",
] }
rustix = { version = "0.38.34", features = ["fs", "mm", "process"] }
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "sync",
    "tracing",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "tracing-log",
] }
wgpu = { version = "22.0.0", default-features = false, features = ["wgsl"] }
clap = { version = "4.5.16", features = ["derive"] }
toml_edit = { version = "0.22.20", features = ["serde"] }
serde = { version = "1.0.208", features = ["derive"] }
diretto = { git = "https://github.com/verdiwm/diretto.git", version = "0.0.3" }
raw-window-handle = "0.6.2"
rand = "0.8.5"
bytemuck = { version = "1.17.0", features = ["derive"] }
reconciler = "0.0.3"
async-stream = "0.3.5"
colpetto = "0.0.3"
waynest = { version = "0.0.9", features = ["server"] }
home = "0.5.9"

[patch.crates-io]
wgpu = { git = "https://github.com/morr0ne/wgpu", branch = "drm-support" }
raw-window-handle = { git = "https://github.com/morr0ne/raw-window-handle", branch = "drm-connector" }
# waynest = { path = "../waynest" }
